[package]
name = "cookie_autoclicker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.1"
mouse_position = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
